---
##################
# default config #
##################
#
# Note: other profiles inherit from here on a per-section bassis (meaning,
# an entire section is replaced, if specified; deeper-level overrides not
# currently supported)

default:
  base_analysis_params:
    HandAnalysisSmart:
      trump_values:     [0, 0, 0, 1, 2, 4, 7, 10]
      suit_values:      [0, 0, 0, 2, 7, 10]
      num_trump_scores: [0.0, 0.2, 0.3, 0.65, 0.9, 1.0]
      off_aces_scores:  [0.0, 0.25, 0.6, 1.0]
      voids_scores:     [0.0, 0.3, 0.7, 1.0]
      scoring_coeff:
        trump_score:      20
        max_suit_score:   7
        num_trump_score:  27
        off_aces_score:   25
        voids_score:      21

  base_strategy_params:
    StrategyRandom:
      rand_seed:        null
    StrategySimple:
      aggressive:       0x0
    StrategySmart:
      hand_analysis:    # keep this empty here, but may be overridden by
                        # individual strategies
      turn_card_value:  [10, 15, 0, 20, 25, 30, 0, 50]
      turn_card_coeff:  [25, 25, 25, 25]
      bid_thresh:       [35, 35, 35, 35, 35, 35, 35, 35]
      alone_margin:     [10, 10, 10, 10, 10, 10, 10, 10]
      def_alone_thresh: [35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35]
      init_lead:
        - next_call_lead
        - draw_trump
        - lead_off_ace
        - lead_to_partner_call
        - lead_to_create_void
        - lead_low_from_long_suit
      subseq_lead:
        - lead_last_card
        - draw_trump
        # maybe swap the next two...
        - lead_off_ace
        - lead_to_partner_call
        - lead_suit_winner
        - lead_to_create_void
        - lead_low_non_trump
        - lead_low_from_long_suit
      part_winning:
        - play_last_card
        - follow_suit_low
        - throw_off_to_create_void
        - throw_off_low
        - play_low_trump
        - play_random_card
      opp_winning:
        - play_last_card
        - follow_suit_high
        - trump_low
        - throw_off_to_create_void
        - throw_off_low
        - play_random_card
    StrategyRemote:
      server_url:       http://localhost:8080
      http_headers:     {}

  base_tourn_params:
    RoundRobin:
      passes:          1
      elim_passes:
      elim_pct:
      reset_elo:       true
      elo_update:      pass
      elo_params:
        elo_db:          elo_rating.db
        use_margin:      false
        d_value:         400
        k_factor:        10
      # base class params
      match_games:     2
      pos_stats:
        - calls
        - calls_made
        - calls_euchred
        - loners_called
        - loners_made
        - loners_failed
        - loners_euchred
        - nl_calls
        - nl_calls_made
        - nl_calls_all_5
        - nl_calls_euchred
      pos_comp_stats:
        - call_make_pct
        - call_euch_pct
        - loner_call_pct
        - loner_make_pct
        - loner_fail_pct
        - loner_euch_pct
        - nl_call_pct
        - nl_make_pct
        - nl_all_5_pct
        - nl_euch_pct
    ChallengeLadder:
      passes:          1
      round_matches:   1
      seeded:          false
      reset_elo:       true
      elo_update:      pass
      elo_params:
        elo_db:          elo_rating.db
        use_margin:      false
        d_value:         400
        k_factor:        10
      # base class params
      match_games:     2
      pos_stats:
        - calls
        - calls_made
        - calls_euchred
        - loners_called
        - loners_made
        - loners_failed
        - loners_euchred
        - nl_calls
        - nl_calls_made
        - nl_calls_all_5
        - nl_calls_euchred
      pos_comp_stats:
        - call_make_pct
        - call_euch_pct
        - loner_call_pct
        - loner_make_pct
        - loner_fail_pct
        - loner_euch_pct
        - nl_call_pct
        - nl_make_pct
        - nl_all_5_pct
        - nl_euch_pct
