---
##################
# default config #
##################
#
# Note: other profiles inherit from here on a per-section bassis (meaning,
# an entire section is replaced, if specified; deeper-level overrides not
# currently supported)

default:
  base_analysis_params:
    HandAnalysisSmart:
      trump_values:     [0, 0, 0, 1, 2, 4, 7, 10]
      suit_values:      [0, 0, 0, 2, 7, 10]
      num_trump_scores: [0.0, 0.2, 0.3, 0.65, 0.9, 1.0]
      off_aces_scores:  [0.0, 0.25, 0.6, 1.0]
      voids_scores:     [0.0, 0.3, 0.7, 1.0]
      scoring_coeff:
        trump_score:      20
        max_suit_score:   7
        num_trump_score:  27
        off_aces_score:   25
        voids_score:      21
  base_strategy_params:
    StrategyRandom:
      seed:             null
    StrategySimple:
      aggressive:       false
    StrategySmart:
      hand_analysis:
        # keep this empty here, but may be overridden by individual strategies
      bid_thresh:       [35, 35, 35, 30, 35, 35, 35, 30]
      alone_margin:     [10, 10, 10, 10, 10, 10, 10, 10]
      def_alone_thresh: [30, 30, 30, 30, 30, 30, 30, 30]
  strategies:
    Alfa 1:
      module_path:      euchplt.strategy
      base_class:       StrategyRandom
    Alfa 2:
      module_path:      euchplt.strategy
      base_class:       StrategyRandom
      strategy_params:
        seed:             99999
    Bravo 1:
      module_path:      euchplt.strategy
      base_class:       StrategySimple
    Bravo 2:
      module_path:      euchplt.strategy
      base_class:       StrategySimple
      strategy_params:
        aggressive:       true
    Charlie 1:
      module_path:      euchplt.strategy
      base_class:       StrategySmart
    Charlie 2:
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        hand_analysis:
          # overrides for HandAnalysisSmart base params
          trump_values:     [0, 0, 0, 1, 2, 4, 7, 10]
          suit_values:      [0, 0, 0, 2, 7, 10]
          num_trump_scores: [0.0, 0.2, 0.3, 0.65, 0.9, 1.0]
          off_aces_scores:  [0.0, 0.25, 0.6, 1.0]
          voids_scores:     [0.0, 0.3, 0.7, 1.0]
          scoring_coeff:
            trump_score:      20
            max_suit_score:   7
            num_trump_score:  23
            off_aces_score:   25
            voids_score:      25
        bid_thresh:       [35, 35, 35, 35, 35, 35, 35, 35]
        alone_margin:     [10, 10, 10, 10, 10, 10, 10, 10]
        def_alone_thresh: [35, 35, 35, 35, 35, 35, 35, 35]
  players:
    Player 0:
      strategy:        Bravo 1
    Player 1:
      strategy:        Bravo 2
    Player 2:
      strategy:        Bravo 1
    Player 3:
      strategy:        Bravo 2
  teams:
    Team 0:
      strategy:        Bravo 1
      players:         ["Player 0", "Player 2"]
    Team 1:
      strategy:        Bravo 2
      players:         ["Player 1", "Player 3"]
