---
default:
  base_strategy_params:
    StrategyBidTraverse:
      play_strat:
      discard_strat:
      bid_prune_strat:
      hand_analysis:
        trump_values:    [0, 0, 0, 0, 1, 3, 7, 10]
    StrategyPlayTraverse:
      bid_strat:
      discard_strat:
      base_play_strat:
      hand_analysis:
      play_analysis:
        trump_values:    [0, 0, 0, 0, 1, 3, 7, 10]

  strategies:
    Bid Model 1:
      module_path:       ml.strategy.bid_traverse
      base_class:        StrategyBidTraverse
      strategy_params:
        play_strat:      Simple i
        discard_strat:
        bid_prune_strat:
        hand_analysis:
    Bid Model 2:
      module_path:       ml.strategy.bid_traverse
      base_class:        StrategyBidTraverse
      strategy_params:
        play_strat:      Simple i
        discard_strat:
        bid_prune_strat: Bid Prune 2
        hand_analysis:
    Bid Prune 2:
      notes:             "yields ~60% bids for pos 7"
      module_path:       euchplt.strategy
      base_class:        StrategySmart
      strategy_params:
        bid_thresh:      [38, 38, 38, 38, 38, 38, 38, 38]
    Play Model 1:
      module_path:       ml.strategy.play_traverse
      base_class:        StrategyPlayTraverse
      strategy_params:
        bid_strat:       Smart 3
        discard_strat:
        base_play_strat: Simple i
        hand_analysis:
    Play Model 2:
      module_path:       ml.strategy.play_traverse
      base_class:        StrategyPlayTraverse
      strategy_params:
        bid_strat:       Smart 3
        discard_strat:
        base_play_strat: Smart 3
        hand_analysis:

  players:
    Bid Model 1:
      strategy:          Bid Model 1
    Bid Model 2:
      strategy:          Bid Model 2
    Discard Model 1:
      strategy:          Discard Model 1
    Discard Model 2:
      strategy:          Discard Model 2
    Play Model 1:
      strategy:          Play Model 1
    Play Model 2:
      strategy:          Play Model 2

  bid_models:
    Bid Model 1:
      data_player:       Bid Model 1
    Bid Model 2:
      data_player:       Bid Model 2

  discard_models:
    Discard Model 1:
      data_player:       Discard Model 1
    Discard Model 2:
      data_player:       Discard Model 2

  play_models:
    Play Model 1:
      data_player:       Play Model 1
    Play Model 2:
      data_player:       Play Model 2
