---
default:
  ml_models:
    bid_model_2-best:
      model_dir:  bid_model_2-best
      deals:      25000
      prob_type:  regression
      label:      points
      quality:    best

    bid_model_2-best-qr:
      model_dir:  bid_model_2-best-qr
      deals:      25000
      prob_type:  quantile
      label:      points
      quality:    best

    bid_model_2-best-mc:
      model_dir:  bid_model_2-best-mc
      deals:      25000
      prob_type:  multiclass
      label:      points
      quality:    best

    play_model_1-best-2:
      model_dir:  play_model_1-best-2
      deals:      1000
      prob_type:  regression
      label:      points_avg
      quality:    best

    play_model_1-best-2-pmx:
      model_dir:  play_model_1-best-2-pmx
      deals:      1000
      prob_type:  regression
      label:      points_max
      quality:    best

    play_model_1-best-3:
      model_dir:  play_model_1-best-3
      deals:      1500
      prob_type:  regression
      label:      points_avg
      quality:    best

    play_model_1-best-3-pmx:
      model_dir:  play_model_1-best-3-pmx
      deals:      1500
      prob_type:  regression
      label:      points_max
      quality:    best
