---
default:
  players:
    Random Player 1a:
      strategy:        Random
    Random Player 1b:
      strategy:        Random
    Simple Player 1a:
      strategy:        Simple i
    Simple Player 1b:
      strategy:        Simple i
    Simple Player 2a:
      strategy:        Simple ii
    Simple Player 2b:
      strategy:        Simple ii
    Simple Player 3a:
      strategy:        Simple iii
    Simple Player 3b:
      strategy:        Simple iii
    Simple Player 4a:
      strategy:        Simple iv
    Simple Player 4b:
      strategy:        Simple iv
    Smart Player 1a:
      strategy:        Smart 1
    Smart Player 1b:
      strategy:        Smart 1
    Smart Player 2a:
      strategy:        Smart 2
    Smart Player 2b:
      strategy:        Smart 2
    Smart Player 3a:
      strategy:        Smart 3
    Smart Player 3b:
      strategy:        Smart 3
    Smart Player 4a:
      strategy:        Smart 4
    Smart Player 4b:
      strategy:        Smart 4
    Smart Player 5a:
      strategy:        Smart 5
    Smart Player 5b:
      strategy:        Smart 5
    Smart Player 6a:
      strategy:        Smart 6
    Smart Player 6b:
      strategy:        Smart 6

  teams:
    Random Team 1:
      strategy:        Random
    Random Team 1b:
      strategy:        Random
    Simple Team 1:
      strategy:        Simple i
    Simple Team 1b:
      strategy:        Simple i
    Simple Team 2:
      strategy:        Simple ii
    Simple Team 2b:
      strategy:        Simple ii
    Simple Team 3:
      strategy:        Simple iii
    Simple Team 3b:
      strategy:        Simple iii
    Simple Team 4:
      strategy:        Simple iv
    Simple Team 4b:
      strategy:        Simple iv
    Smart Team 1:
      strategy:        Smart 1
    Smart Team 1b:
      strategy:        Smart 1
    Smart Team 2:
      strategy:        Smart 2
    Smart Team 2b:
      strategy:        Smart 2
    Smart Team 3:
      strategy:        Smart 3
    Smart Team 3b:
      strategy:        Smart 3
    Smart Team 4:
      strategy:        Smart 4
    Smart Team 4b:
      strategy:        Smart 4
    Smart Team 5:
      strategy:        Smart 5
    Smart Team 5b:
      strategy:        Smart 5
    Smart Team 6:
      strategy:        Smart 6
    Smart Team 6b:
      strategy:        Smart 6
