---
default:
  strategies:
    Random:
      comments:         "base StrategyRandom configuration"
      module_path:      euchplt.strategy
      base_class:       StrategyRandom

    Simple i:
      comments:         "base StrategySimple configuration"
      module_path:      euchplt.strategy
      base_class:       StrategySimple
    Simple ii:
      comments:         "aggressive play for StrategySimple"
      module_path:      euchplt.strategy
      base_class:       StrategySimple
      strategy_params:
        aggressive:       0x01
    Simple iii:
      comments:         "aggressive play for StrategySimple"
      module_path:      euchplt.strategy
      base_class:       StrategySimple
      strategy_params:
        aggressive:       0x02
    Simple iv:
      comments:         "aggressive play for StrategySimple"
      module_path:      euchplt.strategy
      base_class:       StrategySimple
      strategy_params:
        aggressive:       0x03

    Smart 0:
      comments:         "original defaults for HandAnalysisSmart"
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        hand_analysis:
          trump_values:      [0, 0, 0, 1, 2, 4, 7, 10]
          suit_values:       [0, 0, 0, 1, 5, 10]
          num_trump_scores:  [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
          off_aces_scores:   [0.0, 0.2, 0.5, 1.0]
          voids_scores:      [0.0, 0.3, 0.7, 1.0]
          scoring_coeff:
            trump_score:      40
            max_suit_score:   10
            num_trump_score:  20
            off_aces_score:   15
            voids_score:      15
    Smart 1:
      comments:         "base StrategySmart configuration"
      module_path:      euchplt.strategy
      base_class:       StrategySmart
    Smart 2:
      comments:         "raise all bid thresholds"
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        hand_analysis:
          # overrides for HandAnalysisSmart base params
        bid_thresh:       [38, 38, 38, 38, 38, 38, 38, 38]
    Smart 3:
      comments:         "lower all bid thresholds"
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        hand_analysis:
          # overrides for HandAnalysisSmart base params
        bid_thresh:       [32, 32, 32, 32, 32, 32, 32, 32]
    Smart 4:
      comments:         "further lower threshold for dealer position and alone_margin"
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        hand_analysis:
          # overrides for HandAnalysisSmart base params
        bid_thresh:       [32, 32, 32, 28, 32, 32, 32, 28]
        alone_margin:     [8, 8, 8, 8, 8, 8, 8, 8]
    Smart 5:
      comments:         "base config with play adjustment"
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        subseq_lead:
          - lead_last_card
          - draw_trump
          # swapped the next two...
          - lead_to_partner_call
          - lead_off_ace
          - lead_suit_winner
          - lead_to_create_void
          - lead_low_non_trump
          - lead_low_from_long_suit
    Smart 6:
      comments:         "Smart 4 with play adjustment"
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        hand_analysis:
          # overrides for HandAnalysisSmart base params
        bid_thresh:       [32, 32, 32, 28, 32, 32, 32, 28]
        alone_margin:     [8, 8, 8, 8, 8, 8, 8, 8]
        subseq_lead:
          - lead_last_card
          - draw_trump
          # swapped the next two...
          - lead_to_partner_call
          - lead_off_ace
          - lead_suit_winner
          - lead_to_create_void
          - lead_low_non_trump
          - lead_low_from_long_suit

    Hybrid i-1:
      comments:         Simple i (bid) + Smart 1 (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Simple i
        play_strategy:    Smart 1
    Hybrid i-5:
      comments:         Simple i (bid) + Smart 5 (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Simple i
        play_strategy:    Smart 5
    Hybrid 1-i:
      comments:         Smart 1 (bid) + Simple i (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Smart 1
        play_strategy:    Simple i
    Hybrid 2-i:
      comments:         Smart 2 (bid) + Simple i (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Smart 2
        play_strategy:    Simple i
    Hybrid 3-i:
      comments:         Smart 3 (bid) + Simple i (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Smart 3
        play_strategy:    Simple i
    Hybrid 3-ii:
      comments:         Smart 3 (bid) + Simple ii (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Smart 3
        play_strategy:    Simple ii
    Hybrid 3-iii:
      comments:         Smart 3 (bid) + Simple iii (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Smart 3
        play_strategy:    Simple iii
    Hybrid 3-iv:
      comments:         Smart 3 (bid) + Simple iv (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Smart 3
        play_strategy:    Simple iv
    Hybrid 4-i:
      comments:         Smart 4 (bid) + Simple i (play)
      module_path:      euchplt.strategy
      base_class:       StrategyHybrid
      strategy_params:
        bid_strategy:     Smart 4
        play_strategy:    Simple i

    Remote:
      comments:         "base StrategyRemote configuration"
      module_path:      euchplt.strategy
      base_class:       StrategyRemote
