---
##################
# default config #
##################
#
# Note: other profiles inherit from here on a per-section bassis (meaning,
# an entire section is replaced, if specified; deeper-level overrides not
# currently supported)

default:
  base_analysis_params:
    HandAnalysisSmart:
      trump_values:     [0, 0, 0, 1, 2, 4, 7, 10]
      suit_values:      [0, 0, 0, 1, 5, 10]
      num_trump_scores: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
      off_aces_scores:  [0.0, 0.2, 0.5, 1.0]
      voids_scores:     [0.0, 0.3, 0.7, 1.0]
      scoring_coeff:
        trump_score:      40
        max_suit_score:   10
        num_trump_score:  20
        off_aces_score:   15
        voids_score:      15
  base_strategy_params:
    StrategyRandom:
      seed:             null
    StrategySimple:
      aggressive:       false
    StrategySmart:
      hand_analysis:
        # keep this empty here, but may be overridden by individual strategies
      bid_thresh:       [70, 65, 60, 50, 70, 65, 60, 50]
      alone_premium:    [10, 10, 10, 10, 10, 10, 10, 10]
      def_alone_thresh: 70
  strategies:
    Alfa 1:
      module_path:      euchplt.strategy
      base_class:       StrategyRandom
    Alfa 2:
      module_path:      euchplt.strategy
      base_class:       StrategyRandom
      strategy_params:
        seed:             99999
    Bravo 1:
      module_path:      euchplt.strategy
      base_class:       StrategySimple
    Bravo 2:
      module_path:      euchplt.strategy
      base_class:       StrategySimple
      strategy_params:
        aggressive:       true
    Charlie 1:
      module_path:      euchplt.strategy
      base_class:       StrategySmart
    Charlie 2:
      module_path:      euchplt.strategy
      base_class:       StrategySmart
      strategy_params:
        hand_analysis:
          # overrides for HandAnalysisSmart base params
          trump_values:     [0, 0, 0, 1, 2, 4, 7, 10]
          suit_values:      [0, 0, 0, 1, 5, 10]
          num_trump_scores: [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
          off_aces_scores:  [0.0, 0.2, 0.5, 1.0]
          voids_scores:     [0.0, 0.3, 0.7, 1.0]
          scoring_coeff:
            trump_score:      40
            max_suit_score:   10
            num_trump_score:  20
            off_aces_score:   15
            voids_score:      15
        bid_thresh:       [70, 65, 60, 50, 70, 65, 60, 50]
        alone_premium:    [10, 10, 10, 10, 10, 10, 10, 10]
        def_alone_thresh: 70
  players:
    Player 0:
      strategy:        Bravo 1
    Player 1:
      strategy:        Bravo 2
    Player 2:
      strategy:        Bravo 1
    Player 3:
      strategy:        Bravo 2
  teams:
    Team 0:
      strategy:        Bravo 1
      players:         ["Player 0", "Player 2"]
    Team 1:
      strategy:        Bravo 2
      players:         ["Player 1", "Player 3"]
