---
default:
  tournaments:
    Tourney A:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          40
        elim_passes:     10
        elim_pct:        25
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating_500.db
          use_margin:      true
          d_value:         500
          k_factor:        6
      teams:
        - Simple Team 1
        - Simple Team 1b
        - Simple Team 2
        - Simple Team 2b
        - Simple Team 3
        - Simple Team 3b
        - Simple Team 4
        - Simple Team 4b
        - Smart Team 1
        - Smart Team 1b
        - Smart Team 2
        - Smart Team 2b
        - Smart Team 3
        - Smart Team 3b
        - Smart Team 4
        - Smart Team 4b
        - Smart Team 5
        - Smart Team 5b
        - Smart Team 6
        - Smart Team 6b
    Tourney B:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     8
        passes:          60
        elim_passes:     15
        elim_pct:        25
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating_600.db
          use_margin:      true
          d_value:         600
          k_factor:        8
      teams:
        - Team 02
        - Team 04
        - Team 06
        - Team 08
        - Team 10
        - Team 12
        - Team 14
        - Team 16
    Tourney C:
      tourn_class:     ChallengeLadder
      tourn_params:
        match_games:     8
        passes:          20
        round_matches:   10
        reset_elo:       false
        elo_params:
          elo_db:          elo_rating_600.db
          use_margin:      true
          d_value:         600
          k_factor:        8
      teams:
        - Simple Team 1
        - Simple Team 2
        - Simple Team 3
        - Simple Team 4
        - Smart Team 1
        - Smart Team 2
        - Smart Team 3
        - Smart Team 4
        - Smart Team 5
        - Smart Team 6
    Seed D:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          10
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating_500.db
          use_margin:      true
          d_value:         500
          k_factor:        6
      teams:
        - Simple Team 1
        - Simple Team 1b
        - Simple Team 2
        - Simple Team 2b
        - Simple Team 3
        - Simple Team 3b
        - Simple Team 4
        - Simple Team 4b
        - Smart Team 1
        - Smart Team 1b
        - Smart Team 2
        - Smart Team 2b
        - Smart Team 3
        - Smart Team 3b
        - Smart Team 4
        - Smart Team 4b
        - Smart Team 5
        - Smart Team 5b
        - Smart Team 6
        - Smart Team 6b
    Tourney D:
      tourn_class:     ChallengeLadder
      tourn_params:
        match_games:     5
        passes:          10
        round_matches:   20
        reset_elo:       false
        elo_params:
          elo_db:          elo_rating_500.db
          use_margin:      true
          d_value:         500
          k_factor:        6
      teams:
        - Simple Team 1
        - Simple Team 1b
        - Simple Team 2
        - Simple Team 2b
        - Simple Team 3
        - Simple Team 3b
        - Simple Team 4
        - Simple Team 4b
        - Smart Team 1
        - Smart Team 1b
        - Smart Team 2
        - Smart Team 2b
        - Smart Team 3
        - Smart Team 3b
        - Smart Team 4
        - Smart Team 4b
        - Smart Team 5
        - Smart Team 5b
        - Smart Team 6
        - Smart Team 6b
    test:
      comments:        "Short quick profile, doesn't exercise elim_passes"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          2
        elim_passes:     1
        elim_pct:        50
      teams:
        - Smart Team 1
        - Smart Team 2
    prof_random:
      comments:        "Using the base config for StrategyRandom"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     10
        passes:          20
      teams:
        - Random Team 1
        - Random Team 1b
    prof_simple:
      comments:        "Using the base config for StrategySimple"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     10
        passes:          20
      teams:
        - Simple Team 1
        - Simple Team 1b
    prof_smart:
      comments:        "Using the base config for StrategySmart"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     10
        passes:          10
      teams:
        - Smart Team 1
        - Smart Team 1b
    demo:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          20
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating_600.db
          use_margin:      true
          d_value:         600
          k_factor:        8
      teams:
        - Simple Team 1
        - Simple Team 2
        - Simple Team 3
        - Simple Team 4
        - Smart Team 1
        - Smart Team 2
        - Smart Team 3
        - Smart Team 4
        - Smart Team 5
        - Smart Team 6
