---
default:
  tournaments:
    Tourney A:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          40
        elim_passes:     10
        elim_pct:        25
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating_500.db
          use_margin:      false
          d_value:         500
          k_factor:        6
      teams:
        - Team 02
        - Team 03
        - Team 04
        - Team 05
        - Team 06
        - Team 07
        - Team 08
        - Team 09
        - Team 10
        - Team 11
        - Team 12
        - Team 13
        - Team 14
        - Team 15
        - Team 16
        - Team 17
    Tourney B:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     8
        passes:          60
        elim_passes:     15
        elim_pct:        25
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating_600.db
          use_margin:      false
          d_value:         600
          k_factor:        8
      teams:
        - Team 02
        - Team 04
        - Team 06
        - Team 08
        - Team 10
        - Team 12
        - Team 14
        - Team 16
    Tourney C:
      tourn_class:     ChallengeLadder
      tourn_params:
        match_games:     8
        passes:          20
        round_matches:   10
        reset_elo:       false
        elo_params:
          elo_db:          elo_rating_600.db
          use_margin:      false
          d_value:         600
          k_factor:        8
      teams:
        - Team 02
        - Team 04
        - Team 06
        - Team 08
        - Team 10
        - Team 12
        - Team 14
        - Team 16
    Seed D:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          10
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating_500.db
          use_margin:      false
          d_value:         500
          k_factor:        6
      teams:
        - Team 02
        - Team 03
        - Team 04
        - Team 05
        - Team 06
        - Team 07
        - Team 08
        - Team 09
        - Team 10
        - Team 11
        - Team 12
        - Team 13
        - Team 14
        - Team 15
        - Team 16
        - Team 17
    Tourney D:
      tourn_class:     ChallengeLadder
      tourn_params:
        match_games:     5
        passes:          10
        round_matches:   20
        reset_elo:       false
        elo_params:
          elo_db:          elo_rating_500.db
          use_margin:      false
          d_value:         500
          k_factor:        6
      teams:
        - Team 02
        - Team 03
        - Team 04
        - Team 05
        - Team 06
        - Team 07
        - Team 08
        - Team 09
        - Team 10
        - Team 11
        - Team 12
        - Team 13
        - Team 14
        - Team 15
        - Team 16
        - Team 17
    test:
      comments:        "Short quick profile, doesn't exercise elim_passes"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          2
        elim_passes:     1
        elim_pct:        50
      teams:
        - Team 06
        - Team 08
    prof_random:
      comments:        "Using the base config for StrategyRandom"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     10
        passes:          20
      teams:
        - Team 00
        - Team 01
    prof_simple:
      comments:        "Using the base config for StrategySimple"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     10
        passes:          20
      teams:
        - Team 02
        - Team 03
    prof_smart:
      comments:        "Using the base config for StrategySmart"
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     10
        passes:          10
      teams:
        - Team 06
        - Team 07
