---
default:
  tournaments:
    Tourney A:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     5
        passes:          24
        elim_passes:     8
        elim_pct:        33
        reset_elo:       true
        elo_params:
          elo_db:          elo_rating.db
          use_margin:      false
          d_value:         400
          k_factor:        8
      teams:
        - Team 02
        - Team 03
        - Team 04
        - Team 05
        - Team 06
        - Team 07
        - Team 08
        - Team 09
        - Team 10
        - Team 11
        - Team 12
        - Team 13
    test:
      tourn_class:     RoundRobin
      tourn_params:
        match_games:     2
        passes:          8
        elim_passes:     2
        elim_pct:        25
      teams:
        - Team 02
        - Team 03
        - Team 04
        - Team 05
        - Team 06
        - Team 07
        - Team 08
        - Team 09
        - Team 10
        - Team 11
        - Team 12
        - Team 13
